export const NOTI_TYPE = {
  NEW_BOOKING: "NEW_BOOKING",

  SCHEDULE_ADDED: "SCHEDULE_ADDED",
  SCHEDULE_UPDATED: "SCHEDULE_UPDATED",
  SCHEDULE_DELETED: "SCHEDULE_DELETED",

  MOVIE_ADDED: "MOVIE_ADDED",
  MOVIE_UPDATED: "MOVIE_UPDATED",
  MOVIE_DELETED: "MOVIE_DELETED",

  THEATRE_ADDED: "THEATRE_ADDED",
  THEATRE_UPDATED: "THEATRE_UPDATED",
  THEATRE_DELETED: "THEATRE_DELETED",

  SCREEN_ADDED: "SCREEN_ADDED",
  SCREEN_UPDATED: "SCREEN_UPDATED",
  SCREEN_DELETED: "SCREEN_DELETED",

  USER_ADDED: "USER_ADDED",
  USER_UPDATED: "USER_UPDATED",
  USER_DELETED: "USER_DELETED",
};
