export const NOTI_TYPE = {
  NEW_BOOKING: "NEW_BOOKING",
  CANCEL_BOOKING: "CANCEL_BOOKING",

  SCHEDULE_ADDED: "SCHEDULE_ADDED",
  SCHEDULE_UPDATED: "SCHEDULE_UPDATED",
  SCHEDULE_DELETED: "SCHEDULE_DELETED",

  MOVIE_ADDED: "MOVIE_ADDED",
  MOVIE_UPDATED: "MOVIE_UPDATED",
  MOVIE_DELETED: "MOVIE_DELETED",

  THEATRE_ADDED: "THEATRE_ADDED",
  THEATRE_UPDATED: "THEATRE_UPDATED",
  THEATRE_DEACTIVATED: "THEATRE_DEACTIVATED",
  THEATRE_ACTIVATED: "THEATRE_ACTIVATED",

  SCREEN_ADDED: "SCREEN_ADDED",
  SCREEN_UPDATED: "SCREEN_UPDATED",
  SCREEN_DEACTIVATED: "SCREEN_DEACTIVATED",
  SCREEN_ACTIVATED: "SCREEN_ACTIVATED",

  USER_ADDED: "USER_ADDED",
  USER_UPDATED: "USER_UPDATED",
  USER_DEACTIVATED: "USER_DEACTIVATED",
  USER_ACTIVATED: "USER_ACTIVATED",
};
