export const routes = {
  admin: {
    home: "/admin",
    dashboard: "/admin/dashboard",
    demo: "/admin-demo",
    unauthorized: "/unauthorized",
  },
  user: {
    home: "/",
    movies: "movies",
    about: "about",
    contact: "contact",
    order: "order",
    ticketPlan: "ticket-plan",
    booking: "booking",
    bookingHistory: "booking-history",
    ticket: "ticket",
    termsOfUse: "terms-of-use",
    privacyPolicy: "privacy-policy",
    faq: "faq",
  },
  auth: {
    login: "/login",
    signup: "/signup",
    forgotPassword: "/forgot-password",
    otp: "/otp",
    resetPassword: "/reset-password",
  },
  notFound: "/not-found",
};
